### ISSUE TITLE
Firefox and Userscript installation options are broken

### ISSUE THREAD

**Issue by the-nothingman** [bs-detector/bs-detector#169]
### Browser and browser version
[ ] Chrome [X ] Firefox [ ] Other, Version:

### OS and OS version
[ ] Mac [ X] Windows [ ] Linux, Version: 10

Cannot install the firefox version of the addon (from: https://addons.mozilla.org/en-US/firefox/addon/bsdetector/) because Firefox keeps calling it corrupt

also if I try to install the userscript version (from: https://github.com/bs-detector/bs-detector/blob/dev/browserscript/bs-detector.user.js) I get a 404 server not found

**Comment by tomlutzenberger** [comment]
Hi @the-nothingman 

Firefox calls it corrupt, because this version has not been reviewed and therefore not been signed yet. Mozilla needs a quite long time to review new extensions or versions 😞 

If you want to install it from the source, you have to choose the script in the `/ext/` directory. This one is compatible with chrome and firefox.

Hope this was helpful 😊

**Comment by Bastlynn** [comment]
Firefox version has been reviewed as of today (12/26). It is up and ready to go - enjoy!

https://addons.mozilla.org/en-US/firefox/addon/bsdetector/

Once I update with their feedback, I'll be coming back around to the user scripts to port over all of the various updates we've done in the main code to the userscript version.

**Comment by tomlutzenberger** [comment]
Assuming this is resolved, so I'll close the issue for now.
In case of further questions, feel free to get back at us.
