### ISSUE TITLE
Report links to add/remove here!

### ISSUE THREAD

**Issue by selfagency** [bs-detector/bs-detector#53]
Please use this ticket to report any new links to add or to dispute any links that exist in the B.S. Detector dataset.

**Comment by BillyBender** [comment]
Good move. Technology can help in this issue. 
I guessed that your list began with the WashPost article, so I checked to see if truthdig.com and counterpunch.org were on your list.

They are, but they don't belong on the list. Both are Seriously Lefty and present themselves as Opinion Journals, much in the tradition of leftist newsletter watchdog publishers like I.F. Stone, The Nation, etc. 
I haven't read either in the past few months, but have looked at them for years.  I don't often agree with them, but they seriously try to be honest. Check Wikipedia on them.

I noticed that Truthdig has a piece about the WashPost story. You should look at it and follow the links. There's probably a least one that goes to a site you trust. The Post kinda screwed up on this ...

Good luck. BS Detection needs to be done. We need technology, but we also need education.

**Comment by ultramancool** [comment]
{"url": "wikileaks.com", "type": "rumors"},
{"url": "wikileaks.org", "type": "rumors"},

Wikileaks does not publish rumors, they publish leaked information. This should be removed.

**Comment by selfagency** [comment]
wikileaks publishes unconfirmed rumors and innuendo like dnc staffer seth rich was murdered by hillary clinton https://www.washingtonpost.com/local/public-safety/wikileaks-offers-reward-in-killing-of-dnc-staffer-in-washington/2016/08/09/f84fcbf4-5e5b-11e6-8e45-477372e89d78_story.html

**Comment by ultramancool** [comment]
@selfagency That WaPo article you linked doesn't seem to cite any official source at Wikileaks, let alone an actual link to wikileaks.org.

**Comment by selfagency** [comment]
https://twitter.com/wikileaks/status/763041804652539904?lang=en

**Comment by selfagency** [comment]
https://twitter.com/wikileaks/status/763565863861616640?lang=en

**Comment by ultramancool** [comment]
@selfagency That link just says "information leading to a conviction". Nothing about hillary clinton being responsible.

**Comment by selfagency** [comment]
who are you kidding? they posted this while rumors were swirling that rich was behind the dnc leaks and was whacked for it.

**Comment by ultramancool** [comment]
So basically it's exactly like I said - WikiLeaks themselves does nothing to spread rumor, only other people implicate them in it. You yourself are doing it right now. You evil rumor spreader you.

**Comment by selfagency** [comment]
sooooo julian assange can go on tv and imply that rich was a source while rumors are swirling that he was murdered but he's not implicated? this is your idea of critical thinking?

**Comment by ultramancool** [comment]
You got a link for that? I'm interested to see if he actually said that or if you've extrapolated.

**Comment by selfagency** [comment]
it's the newsweek link i posted above

**Comment by blobblobbed** [comment]
Sorry these aren't alphabetized. Made this list on my phone. should all be fresh entries ; )
Add more later if i can. File all of these under "conspiracy" except for the first entry, mediaite.com which i've marked as rumor mill because they'll post pretty much anything.
TO ADD:
mediaite.com RUMOR MILL
conspiracyplanet.com
henrymakow.com/
oathkeepers.org
farmwars.info 
globalresearch.org/ (arm of globalresearch.ca)
newsbud.com
corbettreport.com/
scientologynews.org
fitzinfo.wordpress.com
tarpley.net
rightwingwatch.org
newsbud.com
alternet.org 
crooksandliars.com
morningliberty.com/

Last thing. Judging by the criteria you appear to be going by what constitutes "extreme bias" I would also reccomend adding The Huffington Post to this list. ¯\_(ツ)_/¯

**Comment by blobblobbed** [comment]
Whoops! Hey I just realized scientologynews.org is in that list I posted! For the sake of accuracy, they def wouldn't fall under conspiracy. Extreme Bias, I suppose would be more sufficient. State Sponsored, perhaps? I'd hate to just lump them in here automatically due their reputation, but that site is quite propagandaee

**Comment by BillyBender** [comment]
Propornot, whose list seems to be at the core of your list, has revised [url=http://www.propornot.com/p/the-list.html]their list. It is available here. [/url]
At the bottom of the page, they list the changes 

List v0.0.6: Initial Release
List v0.0.7:
Removed following constructive conversations with outlet operators: aanirfan.blogspot.co.uk, abovetopsecret.com, counterpunch.org, nutritionfacts.org, russia-direct.org
Added: 4thmedia.org, nsnbc.me, presstv.com, theunhivedmind.com, sana.sy

**Comment by BillyBender** [comment]
The New Yorker, one of the most reliable sources of newsy information, [has its own analysis of the WaPost/ProporNot controversy here.  ](http://www.newyorker.com/news/news-desk/the-propaganda-about-russian-propaganda)

**Comment by justic4all** [comment]
Sites which should not be on your list:
1.	Counterpunch
2.	Truthdig
3.	Truthout
4.	Consortium News
5.	Films For Action
6.	Wikileaks
Truthdig and Consortium News in particular are run by well-respected, award-winning investigative journalists.  All of the above except Wikileaks fall into the category of op eds, in the same way as publications like HuffPost Politics, The Nation, The Guardian, etc.
I also agree with ultramancool above re: Wikileaks. In the many thousands of emails they’ve published, not a single one has ever been proven to be false.  If only mainstream media could withstand that level of scrutiny ...
And as far as the single incident you cited of Wikileaks offering a reward for information related to Seth Rich’s murder, seeking actual evidence (as part of their normal course in the pursuit of truth) is exactly the nature of their business. If only mainstream media would go to such lengths before they report stories!  At least Wikileaks is going to the bother of trying to gain actual evidence first before they publish, unlike the political pundits at Fox, CNN and MSNBC.  In fact, Fox News went one step further this week and actually ALTERED evidence to make it fit a narrative. They circulated a highly (and obvious intentionally edited) video of Barack Obama which they said showed him condoning undocumented immigrants voting during the general election. They intentionally cut off the rest of the video that showed him saying just the opposite. So if you’re going to apply a “one strike you’re out” criteria regardless of how many thousands of published pieces in a site are legitimate, then I’m afraid you will also have to add MSNBC, CNN, ABC, NBC and Fox News, Washington Post, NY Times and virtually every single political op ed site to your category of “Fake” or “Rumors”, which would water down and defeat the entire purpose for having your list, which in my mind should only be to identify the most egregious and obvious offenders.
Just in closing, I must say that I am very disturbed by how YOU, by your own acknowledgement, are engaging in the very same practices that you are negatively labeling other sites for doing:  unfairly labeling sites before you even have the evidence to support your claims. You appear to only be relying on rumors and bias to negatively brand some of these sites, something I feel is bordering on slander when you land up unfairly tarnishing the reputation of credible sites before you even have evidence to support your claim or label of them. Moreover, I am wondering who is behind what you’re doing, and am concerned that this is a slippery slope on the way to even more media censorship than already exists. If you’re not already aware, the U.S. has fallen significantly in freedom of press ranking world-wide, in particular because of the government’s effort to silence whistleblowers – such as the ones who provide information to Wikileaks in order to hold power accountable and bring truth to the people.
http://www.cnn.com/2015/02/13/politics/u-s-press-freedom-ranking-obama-administration-leaks/

**Comment by selfagency** [comment]
A few points:

1.   This list is *not* based on the PropOrNot list. This plugin launched a full week before the Washington Post article even came out.
2.   As I have repeatedly stated in the press, on our repo, and on our homepage, the dataset was somewhat indiscrimintely compiled and we are slowly making our way through it. We are also looking to partner with media watchdog groups to provide research to back up our inclusions and classifications so that it is neither arbitrary nor the decision of sole authority. That said, I agree Truthdig, Truthout, and Consortium News do not belong on the list and will remove them.  
3.   Wikileaks has far more than one strike against them. For example: There's [the time they faked a New York Times stoy](https://www.theguardian.com/media/2012/jul/29/bill-keller-fake-column-wikileaks). There's Wikileaks' [failure to verify](http://www.politifact.com/truth-o-meter/article/2016/oct/23/are-clinton-wikileaks-emails-doctored-or-are-they-/) and [redact documents](http://www.advocate.com/media/2016/8/23/wikileaks-outs-saudi-gay-man-rape-victims-and-more).  There's Wikileaks' [open hostility towards fact checkers](https://theintercept.com/2016/08/06/accusing-wikileaks-bias-beside-point/) as Robert Mackey notes. It adds up to a source that cannot be relied upon without additional research and verification, which is why it's flagged as Rumor Mill.
4.    This plugin does not promote censorship, it promotes media literacy. We do not filter out articles, we do not block links, we do not deny access to content. We simply provide warnings to keep your guard up while reading. No one is behind this plugin but me and the volunteer contributors to the repo. I myself am a donor to the Committee to Protect Journalists and the Freedom of the Press Foundation and have given to both Edward Snowden and Chelsea Manning's defense funds. I'm also, in fact, a former donor to Wikileaks. Thus your insinuations are kind of hilarious to me.

**Comment by selfagency** [comment]
@billybender PropOrNot's list is neither at the core nor even included in our list. I will review your other recommendations but I can tell you offhand that Alternet, Mediaite, and CrooksAndLiars do not belong.

**Comment by joeblackwaslike** [comment]
I think much of this list belongs, however I find incredibly odd that sites such as: 
guccifer2.wordpress.com, wikileaks.com, wikileaks.org are included.  Wikileaks is not a source of bias, they publish what they can confirm.  Their twitter can turn into a dumpster fire at times(no arguable), but that's a much different url so why not include that one instead?  Including wikileaks is delegitimizing the kind of service that only wikileaks provides (mass data dumps in searchable form) just in time for a certain president elect to take full advantage of that.  I don't see that as advantageous for our future. Additionally, censoring a private blog that is obviously that simply because they published some data really hurts the credibility of the lists as existing to fight fake news.

It seems this should be a time where we need to put our political differences aside and allow for dissenting opinions and not silence people simply for embarrassing Hillary Clinton with the truth at an inconvenient time.  Your expectation of privacy is almost nonexistent when you seek the highest public office in the nation so anyone doing so is fair game and always has been.  Glenn Greenwald has had much to say about this, but among them one in particular of relevance. https://theintercept.com/2016/10/13/on-wikileaks-journalism-and-privacy-reporting-on-the-podesta-archive-is-an-easy-call/

The spirit of journalism has sought to expose the truth about powerful people and to kill it with a browser extension represents everything that can go wrong with technology.  I would love to see this browser extension become something great and not turn into a red herring such as propornot, but first I would just like to see it be something I feel comfortable promoting others to use.

I'm well aware that this was kind of compiled together and that you're sifting through everything, so I'm not implying any dishonest intentions, just pointing out what seems to be the bias the project is looking to promote the awareness of. :)

**Comment by selfagency** [comment]
@joeblackwaslike I'm an independent, muckraking journalist, and I obviously agree with you about the importance of the press as a check-and-balance on powerful institutions and the importance of leaks. However, Wikileaks is not the only source through which one can leak info. It is merely the most irresponsible one, posting everything online without verifying either its accuracy or redactions to protect the innocent from recrimination. Secure drops are offered by [Propublica](https://www.propublica.org/article/how-to-leak-to-propublica), [the Washington Post](https://www.washingtonpost.com/securedrop/), [the Guardian](https://securedrop.theguardian.com/), and [many more](https://securedrop.org/directory). Flagging Wikileaks as unreliable is not the same as taking a stance against either investigative journalism nor whistleblowing.

**Comment by BillyBender** [comment]
Oops, after posting. I'd noticed that you hadn't absorbed PON's list. 
https://docs.google.com/spreadsheets/d/1an3ACDMKaJofo8PlJUKGMZ_jfQibNgVouMPTcv5bl_0/edit?usp=sharing

Seems like — at some point —  you'll need to link back to the justification for your rankings. Take a look at how rationalwiki does it ...
http://rationalwiki.org/wiki/Fake_news
... a judgement, supported by examples.  Note that their examples implicitly show the readers some of the "tells" of BS.

Ultimately, there would be many advantages if your judgements and justifications could be crowd-sourced ... like a more structured version of, say, Amazon's product reviews. (Interesting to note that PropOrNot seems to spring from the pages of Jeff Bezos' Washington Post. I see from their site that PropOrNot is developing some kind of app.)

Any crowd-sourced approach, of course, raises the possibility of fake reviews ... :) ... but you're going to have to deal with BSD's credibility/authority/honesty/even-handedness no matter how you do it. Just a couple days in, and you're already having to deal with challenges to your judgement. (Fwiw, I agree with you about Wikileaks).

**Comment by NewsThump** [comment]
Hi, you have correctly flagged our site (NewsThump.com) as fake news, but not yet included the reason. Is there any chance you could update the reason as Satire? I love the idea of this plug-in, and I have no problem at all with our site be flagged (as we genuinely don't want people believing what we write, we want them laughing *with* us, not angrily sharing something they've read on our pages). Snopes have classified us as satire twice, and we have a clear disclaimer on our site explaining everything is made up for humour purposes (you can see it here: http://newsthump.com/about-us/). I'm sure you'll get to all the unclassified entries eventually, I just thought I'd try and politely jump the queue - hope that's ok!

**Comment by BigMcLargeHuge** [comment]
Hi @NewsThump thanks for alerting us to this.  We've been scrambling to get all these additions in place.  I'll add that right now.  It will take until the next release for the changes to carry over.  Cheers brother (or sister)!

**Comment by NewsThump** [comment]
@BigMcLargeHuge - thank you.  I can also help you identify a few other UK based satire sites if you'd like, but obviously happy to let you follow your own process. Just let me know...

**Comment by BigMcLargeHuge** [comment]
@NewsThump Please do!  I'll keep an eye on this ticket if you want to let me know right now.  Your site modification has been submitted here #68 and should be integrated on next release (in a matter of days most likely)

**Comment by rdvn** [comment]
Please add folloving slovak/czech conspiracy sites. List is from konspiratori.sk, site that is tracking conspiracy theories, hoaxes, quackery in czech/slovak media space. List could be updated regularly from https://www.konspiratori.sk/assets/downloads/zoznam.txt. Tnx.

vigilantcitizen.com
protiprudu.org
czechfreepress.cz
conspi.cz
nwoo.org
badatel.net
naturalnews.com
afinabul.blog.cz
prvopodstata.com
protiproud.parlamentnilisty.cz
stalo-se.cz
nekorektni-tv.cz
zemejas.cz
pravdive.eu
bezpolitickekorektnosti.cz
freeglobe.parlamentnilisty.cz
svobodnenoviny.eu
novarepublika.cz
antiilluminati.net
vlasteneckenoviny.cz
eurasia24.cz
nemesis.sk
necenzurovane.net
ac24.cz
panobcan.sk
megazine.cz
onlinespravy.eu
alternativnimagazin.cz
priznakytransformace.cz
nazorobcana.sk
je-to-inak.livejournal.com
eurabia.parlamentnilisty.cz
euportal.parlamentnilisty.cz
euserver.parlamentnilisty.cz
proevropu.com
ceskoaktualne.cz
freepub.cz
osud.cz
pravyprostor.cz
ers.blog.cz
tydenikobcanskepravo.parlamentnilisty.cz
casopis-sifra.cz
procproto.cz
svetkolemnas.info
euroasie.info
karolinaloskotova.blog.cz
stopislam.eu
wertyzreport.cz
cestacloveka.sk
mcaris.net
southfront.org
venuska.cz
paratdnes.cz
instory.cz
drsne.sk
hlavnespravy.sk
slovenskeslovo.sk
domacaliecba.sk
ceskozdrave.cz
outsidermedia.cz
radynadzlato.sk
ipribeh.cz
eportal.parlamentnilisty.cz
zpravodaj24.eu
securitymagazin.cz
dolezite.sk
domacamedicina.sk
lajkit.cz
resso.sk
krajskelisty.cz
bulwar.cz
withform.cz
svobodnymonitor.cz
parlamentnelisty.sk
parlamentne-volby-2016.sk
noveslovo.sk
parlamentnilisty.cz
prvnizpravy.parlamentnilisty.cz
nevsedni-svet.cz
halonoviny.com
literarky.cz
eurozpravy.cz
expres.cz

**Comment by BigMcLargeHuge** [comment]
@NewsThump Thanks for the list.  I actually classified the onion as part of a larger pull request a while back that we unfortunately never really got around to merging.  I'll submit a mini one for it.

**Comment by HarleyStaggers** [comment]
Religious satire sites in addition to landoverbaptist.org:

babylonbee.com
christwire.org
eyeofthetiber.com
larknews.com

**Comment by pats2114** [comment]
Hi there. I suggest adding the following:
allenbwest.com (extreme political bias)
youngcons.com (extreme political bias)
usuncut.com (extreme political bias)

I'll keep on the lookout. These are just a few of the ones I've seen trafficking in nonsense.

**Comment by selfagency** [comment]
@rdvn your data has been added to our new [european domain list](https://github.com/selfagency/bs-detector/blob/dev/_shared/data/eu.json). we will be integrating support for european domains and languages soon.

**Comment by cmattoon** [comment]
63red.com
aboveaverage.com
conservative101.com
gatewaypundit.com
patriotjournal.com
proudcons.com
redstate.com

Do you want PR's for these, or just keep 'em here?

**Comment by n4ru** [comment]
theyoungturks.com (Extreme Political Bias)

**Comment by dabockster** [comment]
@n4ru If CNN gets listed in any way, we also should list both Fox News (extreme bias) and MSNBC (potential bias).

**Comment by selfagency** [comment]
I really intended the extreme bias tag for sites that purposefully misrepresent facts for propaganda purposes, not sites that just happen to have a strong political leaning. You can be biased and be telling the truth. The question as to whether a site qualifies is if they're not telling the truth or they're only telling part of the story in order to advance an agenda. So sites like TYT, on the left, and the Blaze, on the right, don't really belong in my view.

**Comment by selfagency** [comment]
I also want to strongly encourage folks to read Brooke Gladstone's ["The Influencing Machine"](https://www.amazon.com/Influencing-Machine-Brooke-Gladstone-Media/dp/0393342468) to get a sense of what we mean when we talk about media bias.

**Comment by selfagency** [comment]
In response to the furor over Wikileaks' inclusion here and on Twitter, I've created a new alert type that will appear in a future release.

<img width="587" alt="screenshot 2016-12-04 16 27 33" src="https://cloud.githubusercontent.com/assets/2541728/20869354/e19ef9cc-ba3e-11e6-9848-2ef7238a5284.png">

Hopefully it's a compromise that fairly addresses people's concerns.

cc: @joeblackwaslike @justic4all @ultramancool

**Comment by TheFourthEstate** [comment]
@selfagency @blobblobbed

I'm a new sign in and caught this feed on Twitter in a WLTaskForce thread. I'm very interested in restoring our 4th Estate of check & balances. I know little of the list or this site and would ask that you provide me a link to the subject list.

I noticed that blobblobbed made mention of NewsBud, and wanted to add my 2 cents.

I have only seen 2 stories from Invesigative Journalist Sibel Edmonds and was very impressed. She documented all that was reported from her cases as an FBI Agent. I found it to be very credible. I have not viewed all of their content, but I plan to because it was refreshing to see real investigative journalism once again.

I wish that blobblobbed would provide information as to why they feel they should be added to a list for conspiracy theories. The story I read was a real conspiracy in that it involved "more than one" government official using the FBI & CIA gathering dirt on politicians & judges for the purpose of blackmailing to set political agenda by the Clintons and to remain "above the law". It was a factual & enlightening information.

As for the Washington Post, it is pretty clear they are not to be trusted.

As for ProporNot, I would like more information about their list. I dont know if I can trust that list and have seen more credible reports poking holes in it.

I would appreciate any links to help me get up to speed with this conversation. I would support any list that would provide the public both sides of a story that has bern truly investigated. 
Also some definition as to the function buttons on this site.

Although Fox has made some mistakes, I'm thankful that they attempt to provide both sides with representatives on with opposing views. I cannot watch CBS, ABC, NBC, CNN without my internal BS meter going off.

I simply want the Truth no matter how uncomfortable it is.
Sometimes the Truth will set you free, but first it will Piss you Off ! (Lol)

Thanks for your help & look forward to restoring The Fouth Estate.

**Comment by TheFourthEstate** [comment]
Sorry
 Just received the intro email and now understand some of the functions on this site. I do not create computer programs, but am interested in this subject. Is this subject #53 ?
I think I inderstand the Help Wanted button. Need more help understanding the Link Addition & Link Dispute buttons.
It may be that I will not need them since my focus is to add input only for a list of reliable & credible news sources.

My take in Wikileaks. I do not see them as a news source per say. I see them as a service of intelligence for journalists to expose the Truth not often found in Mainstream media.
For the record, I am part of the Wikileaks Task Force to report and call out misrepresentations of original Wikileaks source information. I do this voluntarily and have access to one credible whistleblower that can verify information I submit in private to them. If they can confirm or debunk what I submit, then I post on Twitter accordingly. I am @AtomasVictory on Twitter. My profile explains what brought me onto twitter which was motivated by the extreme biased of MSM & the breakdown of professional journalism.

**Comment by doggie015** [comment]
Websites to add:

themercury.com.au
news.com.au
ntnews.com.au
mx.net.au
couriermail.com.au
theaustralian.com.au
dailytelegraph.com.au
heraldsun.com.au

Reasons include, but are not limited to, Extreme Bias, Conspiracy Theory, Junk Science, Hate Group and Clickbait.

**Comment by selfagency** [comment]
@doggie015 see #78

**Comment by DavidMoritz** [comment]
Salon.com
HuffingtonPost.com
Buzzfeed.com

**Comment by RosettasKeys** [comment]
I noticed that anonews.co had been added without a classification. I recommend giving it the "Proceed with Caution" label since their reports may be true, may be true but from a different perspective, completely false, conspiracy theory, or in otherwise not reputable. The site falls into too many categories of "news."

**Comment by doggie015** [comment]
@selfagency how much evidence do you need? Websites? Documentaries? Scholarly papers? What will do it?

https://theconversation.com/murdoch-and-his-influence-on-australian-political-life-16752

https://www.themonthly.com.au/issue/2013/november/1383224400/robert-manne/why-rupert-murdoch-can-t-be-stopped

http://www.hca.westernsydney.edu.au/gmjau/?p=1075

http://anotherangryvoice.blogspot.com.au/2015/04/murdoch-red-ed-miliband.html

http://www.alternet.org/story/151768/12_ways_rupert_murdoch's_media_empire_has_made_the_world_worse

https://www.crikey.com.au/2012/09/24/the-murdoch-paradox-bias-in-climate-reporting/

http://www.imdb.com/title/tt0418038/

http://paperroom.ipsa.org/papers/paper_5190.pdf

**Comment by theothertom** [comment]
Can you add http://www.dailymail.co.uk/ under "Hate Speech" or possibly "Extreme Bias" and "Clickbait" ?

**Comment by MakePublic** [comment]
Hi @selfagency - I really do think this is an excellent development, and spot on with Press TV and Russia Today.  I would like to add (and I see I am not alone)

http://www.dailymail.co.uk/  Hate Speech, Cherry Picking, Misrepresentation, Climate denial, Bullying.
http://www.express.co.uk/ Conspiracy theories over Climate Change, Brexit reporting, fake news.
https://www.thesun.co.uk/ Bullying and intimidation.

I am happy to provide supporting evidence in each case.

I am also minded to very much support Doggie015's list as The Sun is a Murdoch creation that has been associated with an incredible amount of abuse of our citizens over the years.

Chris Clark of Make Public (my real name)

**Comment by hachre** [comment]
The general problem with lists like these is that there can never be a central authority that declares which news is biased and which isn't. This judgement will always be affected by politics, personal opinion, personal political leaning, monetary gains, state interests and so on. 

For example: "www.rt.com" is on the list and marked as "state" - okay. But why aren't all the other (for example European) sites, which are state driven, on this list as well? Are we only interested in putting state-driven propaganda on the list that's outside of the western political reality distortion field which makes it propaganda that clashes with our own? If so, what this will do is make users of the plugin even more susceptible to state-driven propaganda efforts - not less. It will just curate the list of states that get to be the drivers of their opinion.

There has to be a clearly defined, objective process that everyone can look up that defines how sites end up on this list and why. This process has to be public and verifiable. I think creating this process will be the hardest part of creating this entire project.

**Comment by danhklein** [comment]
Hey @hachre, I don't entirely disagree with what you're saying (You should take a look at the gitter conversation on the data). Right now the 'State News" tag is limited to "Sources in repressive states operating under government sanction."

**Comment by hachre** [comment]
danhklein: Alright, thanks for the info!

**Comment by fcurella** [comment]
A couple of Italian national newspapers are classified as 'satire', when they are actual legit newspapers. They might be biased, but I wouldn't categorize them as satire.

The specific cases are:

* [ilmessaggero.it](https://github.com/selfagency/bs-detector/blob/master/_shared/data/data.json#L697): See [Wikipedia entry](https://en.wikipedia.org/wiki/Il_Messaggero)
* [ilfattoquotidiano.it](https://github.com/selfagency/bs-detector/blob/master/_shared/data/data.json#L694): See [Wikipedia entry]

**Comment by selfagency** [comment]
thanks @fcurella — we are looking for qualified folks in europe to review the european dataset. i will remove those two entries based on the info you've provided.

**Comment by Syberpathetic** [comment]
I would like to submit [gazeteman.com](http://www.gazeteman.com/) to be filed under Clickbait and Junk Science. http://www.gazeteman.com/

**Comment by selfagency** [comment]
@Syberpathetic definitely clickbait, thanks

**Comment by doggie015** [comment]
@selfagency Still awaiting a response

**Comment by selfagency** [comment]
@doggie015 we'll be reviewing those links and your references as part of our process of classification. please be patient as it is taking some time.

**Comment by mschenk** [comment]
Can you remove http://thedailywtf.com from the list?  It is just a humor site where programmers post IT  horror stories.  Doesn't have anything to do with politics, pseudoscience or extremism at all...

How the site got included in the list is probably a good story for The Daily WTF actually... :-)

**Comment by raichiss** [comment]
Not sure why [corbettreport.com](http://www.corbettreport.com) made the list - I would love some elaboration on your criteria.

**Comment by selfagency** [comment]
@raichiss as stated on our website and readme, our initial dataset was compiled from existing lists of questionable news sources and is currently under review. we are planning to remove sometime today all sites that have not yet been reviewed. however, a quick glance at [corbettreport.com](https://www.corbettreport.com/tag/911/) reveals that he is a 9/11 truther, which is justification for listing him under conspiracy theory.

**Comment by AvangionQ** [comment]
Please check this site ... http://www.palmerreport.com

**Comment by HolmesInOz** [comment]
please remove theage.com.au it's mainstream news, not even owned by murdoch

or alternatively you could add the murdoch papers

thedailytelegraph.com.au
theaustralian.com.au

**Comment by BigMcLargeHuge** [comment]
@HolmesInOz theage.com.au has been removed from our recently revised list of sources. Should be merged with PR #117

**Comment by anddman** [comment]
http://dietagespresse.com/
"dietagespresse.com":                                  {"language": "de", "type": "satire", "notes": ""},
Official disclaimer: "Die Tagespresse ist eine österreichische Satirezeitung. Alle Artikel sind frei erfunden."
Google translation: "The daily press is an Austrian satire newspaper. All articles are fictitious."

https://www.unzensuriert.at/
"unzensuriert.at":                                  {"language": "de", "type": "bias", "notes": ""},
Strong bias toward right-wing party FPÖ of Austria. German Wikipedia article (https://de.wikipedia.org/wiki/Unzensuriert.at) goes into more detail. very slightly corrected Google translation can be found here: http://pastebin.com/n5VW43qU

**Comment by Sputnikian** [comment]
http://www.bayonpearnik.com/
fake news, rumor mill, conspiracy theory, extreme bias

**Comment by cdome** [comment]
This page (https://echo24.cz/a/isYwV/42-ceskych-a-slovenskych-webu-ktere-siri-ruske-lzi) contains list of 42 czech and slovak webs spreading conspiracy and Russian propaganda. Some of them are already on your list, some of them are missing:
www.svetkolemnas.info
www.zvedavec.org
www.ac24.cz
www.rodinajezaklad.sk
www.stopautogenocide.sk
www.osud.cz
http://czech.ruvr.ru/
http://slovak.ruvr.ru
www.zemavek.sk
http://panobcan.sk/
www.czechfreepress.cz
http://vaseforum.sk/blog/
www.slobodnyvysielac.sk
www.hlavnespravy.sk
www.badatel.sk, www.badatel.net
www.protiprudu.org
www.beo.sk
http://obcianskytribunal.sk/blog/
www.sho.sk
www.voxvictims.com/
http://freeglobe.parlamentnilisty.cz/
www.magnificat.sk
www.freepub.cz
http://vkpatriarhat.org.ua/cz/
www.spolocnostsbm.com
http://svobodnenoviny.eu
http://www.auria.sk/blog/
http://afinabul.blog.cz/
www.dolezite.sk
www.inespravy.sk
www.nadhlad.com
www.ze-sveta.cz
http://nwoo.org
http://orgo-net.blogspot.sk
www.cez-okno.net
www.vlastnihlavou.cz
www.neskutocne.sk
www.bezpolitickekorektnosti.cz
www.eiaktivity.sk
www.nazorobcana.sk
www.alternews.cz
http://pravdive.eu/index.php
www.aeronet.cz
www.slovenskeslovo.sk

**Comment by fredvries** [comment]
Dutch conspiracy sites
- www.revolutionaironline.com (frequently links to Alex Jones, thinks he's falsely procecuted, in 'exile' in Ireland)
- https://rechtiskrom.wordpress.com (thinks that a murderer who confessed and is sentenced isn't the real murderer, stalking the family of the victim)
- www.niburu.nl (site believes in everything)
- www.wanttoknow.nl (site believes in everything, like vaccines are intended to kill)
- www.boublog.nl (thinks that a convicted drugs dealer is innocent, believes pizzagate is real news, etc)

**Comment by peppersgc** [comment]
This is literally fake news.

http://www.dailymail.co.uk/tvshowbiz/article-4021280/Grand-Theft-Auto-Clarkson-s-TV-comeback-illegally-downloaded-history-viewers-pirating-episode-7-9million-times.html

**Comment by peppersgc** [comment]
https://www.wikileaks.org/ - Is NOT a news site. It releases verified information gathered in the public interests. The only information site in history that throughout its entire existence (10 years) has never had to retract disseminated information for being proven false.

http://drudgereport.com/ - A news aggregate site. Almost everything listed there are links to other sites. If any story linked is proven to be false, it is quickly removed and denounced as fake. The very definition of a good news site.

**Comment by peppersgc** [comment]
Lies embedded in stories also constitute heavily biased fake news.

http://www.nytimes.com/2016/11/19/us/mike-pence-hamilton.html

**Comment by peppersgc** [comment]
Lies embedded in stories also constitute heavily biased fake news.

http://www.huffingtonpost.com/entry/mike-pence-booed-hamilton_us_582fbe42e4b030997bbf9782?

**Comment by OlivierLabbe** [comment]
Salon.com :: Extreme Bias
HuffingtonPost.com :: Clickbait
Buzzfeed.com :: Clickbait

**Comment by sleslie** [comment]
This page (http://fusion.net/story/375283/belle-fourche-pipeline-spill-belfield-north-dakota/?utm_source=fusiondaily&utm_medium=email&utm_campaign=12122016) was flagged for "Satire." There is definitely nothing satirical about this story. I can't speak to the site as a whole, but if important unbiased stories like this are getting flagged simply because of stories on another part of the domain, it does throw some of the plugins overall logic into question.

**Comment by MakePublic** [comment]
Well, if so would not the flagged category be generally correct - maybe 
drop the 'satire' bit?

> WARNING: THIS MAY NOT BE A RELIABLE SOURCE. (SATIRE)

Chris

**Comment by sleslie** [comment]
So it's not a site I frequent a lot but I just took some time to go through it. It looks to me to be reporting factual stories in a non-hyperbolic or biased way. It certainly is curated to report stories of interest to "progressives" but if you're flagging sites simply for having a target audience, I'm not sure what to say. There is no evidence at all that this site is either "satire" or "fake news" and indeed I'd ask anyone making that claim to point me to specific stories as evidence. 

N.B. I have ZERO relation to this site, and don't have a dog in this fight other than the fact that I work supporting public libraries and so am keenly interested in literacy and education, and do see people's apparent ability to detect "fake news" as troubling. I submitted this because I came across what I felt was an inappropriate flagging and was interested to learn about the process through which the plugins flagging rules are creted and maintained. Cheers, Scott

**Comment by tomlutzenberger** [comment]
# Announcement

The handling and maintenance of site data is a very large task that is separate from developing code.

For this purpose, a work-group has been founded where experts like professors and librarians may review the submitted sources in a neutral and nonbiased way using their professional experience. That group is named Open Sources and is accepting volunteers at this time.

When those sites get added, B.S. Detector will load them through an API and use them in the browser extension(s).

Please submit your links to [OpenSources.co](http://www.opensources.co).

**Comment by selfagency** [comment]
B.S. Detector is no longer responsible for maintaining the dataset powering our flagging engine. To suggest or dispute entries, [file an issue with OpenSources](https://github.com/bigmclargehuge/opensources/issues).
